Repository NataGildry/team-challenge-online-shop, pull requests merged in 2025-03, with the labels that each got.

#5 Create Folder Structure
  README.md
  apps/backend/.gitkeep
  apps/frontend/.gitkeep
  docs/.gitkeep
Labels: 📖type:documentation

#7 Setup FE
  .editorconfig
  .vscode/extensions.json
  apps/frontend/.gitignore
  apps/frontend/.prettierignore
  apps/frontend/.prettierrc
  apps/frontend/apps/anx-store/eslint.config.mjs
  apps/frontend/apps/anx-store/jest.config.ts
  apps/frontend/apps/anx-store/project.json
  apps/frontend/apps/anx-store/public/favicon.ico
  apps/frontend/apps/anx-store/src/app/app.component.html
  apps/frontend/apps/anx-store/src/app/app.component.scss
  apps/frontend/apps/anx-store/src/app/app.component.spec.ts
  apps/frontend/apps/anx-store/src/app/app.component.ts
  apps/frontend/apps/anx-store/src/app/app.config.server.ts
  apps/frontend/apps/anx-store/src/app/app.config.ts
  apps/frontend/apps/anx-store/src/app/app.routes.ts
  apps/frontend/apps/anx-store/src/app/nx-welcome.component.ts
  apps/frontend/apps/anx-store/src/index.html
  apps/frontend/apps/anx-store/src/main.server.ts
  apps/frontend/apps/anx-store/src/main.ts
  apps/frontend/apps/anx-store/src/server.ts
  apps/frontend/apps/anx-store/src/styles.scss
  apps/frontend/apps/anx-store/src/test-setup.ts
  apps/frontend/apps/anx-store/tailwind.config.js
  apps/frontend/apps/anx-store/tsconfig.app.json
  apps/frontend/apps/anx-store/tsconfig.editor.json
  apps/frontend/apps/anx-store/tsconfig.json
  apps/frontend/apps/anx-store/tsconfig.spec.json
  apps/frontend/eslint.config.mjs
  apps/frontend/jest.config.ts
  apps/frontend/jest.preset.js
  apps/frontend/nx.json
  apps/frontend/package-lock.json
  apps/frontend/package.json
  apps/frontend/tsconfig.base.json
Labels: 🖥️aspect:fe

#11 chore: update git ignore
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  apps/frontend/.prettierrc
  apps/frontend/apps/anx-store/project.json
  apps/frontend/apps/anx-store/src/index.html
Labels: 🖥️aspect:fe

#13 Setup basic BE project with test endpoint
  .gitignore
  apps/backend/.gitkeep
  apps/backend/FakedOutShop.API/FakedOutShop.API.csproj
  apps/backend/FakedOutShop.API/MyEndpoint.cs
  apps/backend/FakedOutShop.API/Program.cs
  apps/backend/FakedOutShop.API/Properties/launchSettings.json
  apps/backend/FakedOutShop.API/appsettings.json
  apps/backend/FakedOutShop.API/appsettingsDevelopment.json
  apps/backend/FakedOutShop.sln
Labels: 🛠️ aspect:be

#16 Modify basic BE project
  apps/backend/FakedOutShop.API/Controllers/UserController.cs
  apps/backend/FakedOutShop.API/FakedOutShop.API.csproj
  apps/backend/FakedOutShop.API/MyEndpoint.cs
  apps/backend/FakedOutShop.API/Program.cs
  apps/backend/FakedOutShop.Application/Abstractions/IUserService.cs
  apps/backend/FakedOutShop.Application/DTOs/ResponseDto.cs
  apps/backend/FakedOutShop.Application/FakedOutShop.Application.csproj
  apps/backend/FakedOutShop.Application/Models/Services/UserService.cs
  apps/backend/FakedOutShop.Domain/FakedOutShop.Domain.csproj
  apps/backend/FakedOutShop.Infrastructure/Data/DependencyInjection.cs
  apps/backend/FakedOutShop.Infrastructure/FakedOutShop.Infrastructure.csproj
  apps/backend/FakedOutShop.UnitTests/FakedOutShop.UnitTests.csproj
  apps/backend/FakedOutShop.UnitTests/UnitTest1.cs
  apps/backend/FakedOutShop.sln
Labels: 🛠️ aspect:be
